version: '3'

services:
    # MySQL
    mysql:
        restart: always
        image: mysql:8.0
        ports:
            - "3306:3306" # mysql
            - "8280:80" # mysql admin
        container_name: mysql_host
        environment:
            MYSQL_DATABASE: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_ROOT_PASSWORD: "test"    
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - "./init/:/docker-entrypoint-initdb.d/"
            - "./mysql/data:/var/lib/mysql"
            - "./mysql/conf/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf"
        # ports:
        #     - 3306:3306
        networks:
            - mysqlnetwork

         
networks:
    mysqlnetwork:
        driver: bridge