spring:
  application:
    name: kafka-demo
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    consumer:
      bootstrap-servers: localhost:9092

